### ISSUE TITLE
couldn't connect 130.237.36.25:2907

### ISSUE THREAD

**Issue by mosquitoam** [smarc-project/rosinstall#7]
Hello, I am trying to install SMARC software packages by rosinstall. While when I run `sudo apt-get update`, it showed that I couldn't connect 130.237.36.25:2907. I had checked my network.

**Comment by KKalem** [comment]
@nilsbore @Jollerprutt is the server down? I had the same problem before at some point.

**Comment by mosquitoam** [comment]
Thanks, I've been able to connect to the server

**Comment by Jollerprutt** [comment]
Yes sorry, the server was down but it's back up now.

**Comment by tiko5000** [comment]
Seems to be down again, I have the same issue right now.

**Comment by Jollerprutt** [comment]
Yes sorry, it's back up now.
